config/routes.rb
Rails.application.routes.draw do
  resource :notam, only: [] do
    post :show, on: :collection
    get :upload, on: :collection
  end

  root to: redirect('/notam/upload')
end

app/models/notice.rb
class Notice < ActiveRecord::Base
  serialize :fields

  def parse
    # Split all lines
    raw_lines = self.text.split("\n")

    # Separate identification and created/source
    line_identifier = raw_lines.shift
    line_source     = raw_lines.pop
    line_created    = raw_lines.pop

    # Parse identifier
    if m = line_identifier.match(/(\w\d+\/\d{2}) NOTAM([N|C|R])(?: (\w\d+\/\d{2}))?/)
      self.identifier = m[1]
      self.type = m[2]
      self.reference_id = Notice.find_by(identifier: m[3]).try(:id)
    end

    self.source = line_source.gsub('SOURCE: ', '')

    # Parse created
    self.created_at = Time.use_zone('UTC') { Time.zone.parse(line_created.gsub('CREATED: ', '')) }

    # Normalise remaining text
    raw_data = raw_lines.join(' ')

    # Find our fields
    fld_headers = raw_data.scan(/([A-GQ])\)/).flatten
    fld_data    = raw_data.split(/[A-GQ]\) /)[1..-1].map(&:strip)

    self.fields = Hash[fld_headers.zip(fld_data)]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notams_controller.rb
class NotamsController < ApplicationController
  def upload
  end

  def show
    # Parse uploaded notams
    if params[:file] or params[:data]
      raw = if params[:file]
        params[:file].read
      else
        params[:data].gsub("\r\n", "\n")
      end

      notices = raw.split("\n\n").collect{|n| Notice.new(text: n)}
      # Parse notices
      notices.map(&:parse)

      # Select only notices with aerodome hours
      notices.select!{|n| n.fields['E'] && n.fields['E'].match(/AERODROME HOURS OF OPS\/SERVICE/)}

      # Build tabular data
      @aerodomes = Hash.new{|h,k| h[k] = []}
      @weekdays = %w{MON TUE WED THU FRI SAT SUN}
      re = Regexp.new(/(MON|TUE|WED|THU|FRI|SAT|SUN)(?:-(MON|TUE|WED|THU|FRI|SAT|SUN))? ?([, \d-]+|CLOSED|CLSD)/)

      notices.sort_by(&:created_at).each do |notice|
        # Parse opening hours
        open = notice.fields['E'].scan(re)
        open.each do |m|
          (@weekdays.index(m[0])..(@weekdays.index(m[1])||@weekdays.index(m[0]))).each do |i|
            @aerodomes[notice.fields['A']][i] = m[2].split(/, | /).map(&:strip)
          end
        end
      end
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Notam
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      = yield

app/views/notams/show.html.haml
.row
  .col-sm-10.col-sm-offset-1
    %table.table
      %thead
        %tr
          %th Aerodrome
          - @weekdays.each do |wd|
            %th= wd
      %tbody
        - @aerodomes.each do |ad, weekdays|
          %tr
            %td= ad
            - weekdays.each do |open|
              %td= open.join('<br />').html_safe if open.kind_of?(Array)

app/views/notams/upload.html.haml
.row
  .col-sm-6.col-sm-offset-4
    %h1 NOTAM
    %p Please upload NOTAM data to show parsed information

    = form_tag notam_path, method: :post, multipart: true do
      %p Copy and paste NOTAM data here
      = text_area_tag :data, nil, rows: 3, cols: 45
      %p or upload text file containing NOTAM data
      = file_field_tag :file
      %br
      = button_tag type: 'submit', class: 'btn btn-lg btn-primary' do
        = icon('cloud-upload')
        Parse